In [3]:
import numpy as np 
myPythonList = [1,9,8,3]

In [4]:
numpy_array_from_list = np.array(myPythonList)

In [5]:
numpy_array_from_list

array([1, 9, 8, 3])

In [6]:
a  = np.array([1,9,8,3])

In [7]:
numpy_array_from_list + 10

array([11, 19, 18, 13])

In [12]:
d = np.array([
    [[1, 2,3],
      [12,13,14],
        [4, 5, 6]],
    [[7, 8,9],
      [12,13,14],
        [10, 11, 12]],
                  ])
print(d.shape)

(2, 3, 3)


In [13]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [21]:
np.zeros((2,5), dtype=np.int64)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [23]:
s = np.ones((1,4,8), dtype=np.int16)
print(s)

[[[1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]]]


In [24]:
s.reshape(4,1,8)

array([[[1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1]]], dtype=int16)

In [26]:
s.reshape(8,2,2)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

In [27]:
s.flatten()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [32]:
normal_array = np.random.normal(8, 0.4, 10)
print(normal_array)

[7.90635145 7.99462906 7.54355354 7.95263797 7.70753075 8.36879285
 8.84084498 7.75549021 8.49308319 8.28307178]


In [36]:
np.arange(5, 20,3)

array([ 5,  8, 11, 14, 17])

In [42]:
np.linspace(4.5, 5.0, num=20)

array([4.5       , 4.52631579, 4.55263158, 4.57894737, 4.60526316,
       4.63157895, 4.65789474, 4.68421053, 4.71052632, 4.73684211,
       4.76315789, 4.78947368, 4.81578947, 4.84210526, 4.86842105,
       4.89473684, 4.92105263, 4.94736842, 4.97368421, 5.        ])

In [43]:
np.linspace(4.5, 5.0, num=10, endpoint=True)

array([4.5       , 4.55555556, 4.61111111, 4.66666667, 4.72222222,
       4.77777778, 4.83333333, 4.88888889, 4.94444444, 5.        ])

In [45]:
np.logspace(3.0, 4.0, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

In [46]:
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize

16